"""empty message

Revision ID: 34256522985f
Revises: 8e98227d8205
Create Date: 2021-07-13 12:59:01.777375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34256522985f'
down_revision = '8e98227d8205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product', sa.String(), nullable=False))
    op.drop_constraint('cart_product_id_fkey', 'cart', type_='foreignkey')
    op.drop_column('cart', 'product_id')
    op.add_column('stripe_product', sa.Column('stripe_product_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_product', 'stripe_product_id')
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('cart_product_id_fkey', 'cart', 'user', ['product_id'], ['id'])
    op.drop_column('cart', 'product')
    # ### end Alembic commands ###
