"""added bio attribute to User model

Revision ID: 584b793fc5d0
Revises: c951ca9fa239
Create Date: 2021-07-09 10:26:55.526741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584b793fc5d0'
down_revision = 'c951ca9fa239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
